package sage.plugin;

import java.io.File;
import java.io.FileWriter;
import java.io.Writer;
import java.util.Date;

import sage.Sage;

public class GradleSettingsBuilder implements Runnable {

	public void run() {
		File f = new File(CorePluginManager.JAR_STAGE_ROOT, "settings.gradle");
		f.delete();
		StringBuilder sb = new StringBuilder();
		sb.append(String.format("// Generated by SageTV on %s\n", new Date()));
		sb.append("// DO NOT EDIT THIS FILE\n// It is auto generated by SageTV\n\n");
		sb.append("include 'CORE'\n");
		for(PluginWrapper p : CorePluginManager.getInstance().getMyPlugins())
			sb.append(String.format("include '%s'\n", p.getId()));
		Writer w = null;
		try {
			w = new FileWriter(f);
			w.append(sb);
		} catch(Throwable t) {
			Sage.printStackTrace(t);
		} finally {
			if(w != null)
				try {
					w.close();
				} catch(Throwable t) {
					Sage.printStackTrace(t);
				}
		}
	}
}
